MxOnline/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
import xadmin
from django.views.static import serve
from users.views import ActiveUserView, IndexView
from MxOnline.settings import MEDIA_ROOT
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('mxonline/xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # 用户url
    path('users/', include('users.urls', namespace='users')),
    # 用户激活
    re_path(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    # 图片验证码
    path('captcha/', include('captcha.urls')),
    # 课程机构
    path('org/', include('organization.urls', namespace='organization')),
    # 课程url
    path('course/', include('course.urls', namespace='course')),
    # 配置上传文件处理函数
    re_path(r'media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),

    # 富文本url
    re_path(r'^mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 全局404
handler404 = 'users.views.page_not_found'
# 全局500
handler500 = 'users.views.page_error'

apps/course/urls.py
from django.urls import path
from .views import *
app_name = 'course'
urlpatterns = (
    path('course_list/', CourseListView.as_view(), name='course_list'),
    path('course_detail/<int:course_id>/', CourseDetailView.as_view(), name='course_detail'),
    # 开始学习
    path('course_video/<int:course_id>/', CourseVideoView.as_view(), name='course_video'),
    # 评论界面
    path('course_video_comment/<int:course_id>/', CommentCourseView.as_view(), name='course_video_comment'),
    # 添加评论
    path('add_comment/', AddCommentsView.as_view(), name='add_comment'),

    path('video/<int:video_id>/', VideoView.as_view(), name='video_play'),

)

apps/organization/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'organization'
urlpatterns = [
    # 课程机构url
    path('list/', OrgListView.as_view(), name='org_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    path('org_home/<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    path('org_course/<int:org_id>/', OrgCourseView.as_view(), name='org_course'),
    path('org_desc/<int:org_id>/', OrgDescView.as_view(), name='org_desc'),
    path('org_teacher/<int:org_id>/', OrgTeacherView.as_view(), name='org_teacher'),
    # 机构收藏
    path('add_fav/', AddFavView.as_view(), name='add_fav'),
    # 讲师列表
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),

    path('teacher/detail/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
    # 分享
    path('share/message/', SendShareEmailView.as_view(), name='share'),
]

apps/users/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'users'
urlpatterns = (
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # 忘记密码
    path('forget/', ForgetPwdView.as_view(), name='forget'),
    re_path(r'^reset/(?P<reset_code>.*)/$', ResetPwdView.as_view(), name='user_reset'),
    path('reset/', ResetView.as_view(), name='reset_pwd'),
    # 登出
    path('logout/', OutLoginView.as_view(), name='logout'),
    # 用户信息
    path('user_info/', UserInfoView.as_view(), name='user_info'),
    # 用户头像
    path('user/image/', UploadImageView.as_view(), name='user-image'),
    # 用户密码修改
    path('update/pwd/', ModifyPwdView.as_view(), name='update-pwd'),
    # 用户邮箱修改，发送邮箱验证码
    path('sendemail_code/', SendEmailView.as_view(), name='sendemail_code'),
    # 用户邮箱修改
    path('update_email/', ModifyEmailView.as_view(), name='update_email'),
    # 修改用户信息
    # path('info/', UserInfoView.as_view(), name='info'),
    # 用户课程
    path('user_course/', UserCourseView.as_view(), name='user_course'),
    # 用户收藏(机构，教师，课程)
    # re_path(r'^user_fav/(?P<fav_type>.*)/$', UserFavView.as_view(), name='user_fav'),
    # 用户收藏机构
    path('user_fav/org/', UserFavOrgView.as_view(), name='user_fav_org'),
    # 教师
    path('user_fav/teacher/', UserFavTeacherView.as_view(), name='user_fav_teacher'),
    # 课程
    path('user_fav/course/', UserFavCourseView.as_view(), name='user_fav_course'),
    # 用户消息
    path('user_message/', UserMessageView.as_view(), name='user_message'),

)

apps/course/models.py
from django.db import models
from datetime import datetime
from organization.models import Teacher, CourseOrg
from users.models import UserProfile
from mdeditor.fields import MDTextField

# Create your models here.


class CourseCategory(models.Model):
    name = models.CharField(max_length=64, verbose_name="课程类别名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程类别"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='教授机构', null=True, blank=True, on_delete=models.CASCADE)
    course_teacher = models.ForeignKey(Teacher, verbose_name='教授讲师', null=True, blank=True, on_delete=models.CASCADE)
    course_category = models.ForeignKey(CourseCategory, verbose_name="课程类别", on_delete=models.CASCADE)
    name = models.CharField(max_length=64, verbose_name="课程名")
    desc = models.CharField(max_length=256, verbose_name="课程描述")
    detail = MDTextField(verbose_name='课程详情')
    degree = models.CharField(verbose_name='难度', choices=(('cj', "初级"), ('zj', "中级"), ('gj', "高级")), max_length=32)
    learn_time = models.IntegerField(default=0, verbose_name="学习时长")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏人数")
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name="封面", blank=True)
    tag = models.CharField(default='', max_length=20, verbose_name="课程标签")
    click_nums = models.IntegerField(default=0, verbose_name="浏览量")
    known = MDTextField(verbose_name='课程须知', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_lesson(self):
        return self.lesson_set.all().count()

    def get_course_user(self):
        return self.usercourse_set.all()[:5]

    def save(self, *args, **kwargs):
        """
        将新增加的课程添加到课程机构
        :param args: 
        :param kwargs: 
        :return: 
        """
        self.course_org.course_nums += 1
        # 调用父类的 save 方法将数据保存到数据库中
        super(Course, self).save(*args, **kwargs)
        
    def increase_click_nums(self):
        self.click_nums += 1
        self.save(update_fields=['click_nums'])
        
    def increase_fav_nums(self):
        self.fav_nums += 1
        self.save(update_fields=['fav_nums'])
        
    def increase_students_nums(self):
        self.students += 1
        self.save(update_fields=['students'])


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name="章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course.name + ' ' + self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name="视频名")
    content = models.FileField(upload_to="videos/", null=True, blank=True, verbose_name="视频内容")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")
    # url = models.CharField(max_length=128, verbose_name="访问地址", default='')

    def __str__(self):
        return self.name

    def get_video_course(self):
        return self.lesson.course.name
    get_video_course.short_description = '课程名称'

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=32, verbose_name="名称")
    download = models.FileField(upload_to='course/resource/%X', verbose_name="资源")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 课程公告
class CourseAnnouncement(models.Model):
    course = models.ForeignKey(Course, verbose_name='公告课程', on_delete=models.CASCADE)
    text = models.CharField(max_length=200, default='', verbose_name='课程公告')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程公告"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course.name + '的课程公告。'

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}慕学在线网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block customer_css %}{% endblock %}


</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            {% if request.user.is_authenticated %}
            <div class="top">
                <div class="wp">
                    <div class="fl">
                        <p>服务电话：<b>111111</b></p>

                    </div>

                    <!--登录后跳转-->
                    <div class="personal">
                        {% if request.user.message.count > 0 %}

                            <a style="margin-left: 20px;" href="{% url 'users:user_message' %}">
                                <div class="msg-num"><span id="MsgNum">{{ request.user.message.count }}</span></div>
                            </a>
                            {% endif %}
                            <dl class="user fr">
                                <dd><img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                                    <dd>
{#                                        <h2>{{ user.name }}</h2>#}
                                        <p>{{ user.nick_name }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                            </div>


                            </div>
                            </div>
                        {% else %}
                            <div class="top">
                                <div class="wp">
                                    <div class="fl"><p>服务电话：<b>111111</b></p></div>
                                    <!--登录后跳转-->

                                    <a style="color:white" class="fr registerbtn"
                                       href="{% url 'users:register' %}">注册</a>
                                    <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>

                                </div>
                            </div>
                        {% endif %}

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>
            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% if link == 'index' %}class="active"{% endif %}><a href="{% url 'index' %}">首页</a>
                            </li>
                            <li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
                                <a href="{% url 'course:course_list' %}">
                                    公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                                </a>
                            </li>
                            <li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
                                <a href="{% url 'organization:teacher_list' %}">授课教师</a>
                            </li>
                            <li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %}><a
                                    href="{% url 'organization:org_list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_body %}

{% endblock %}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
                {#                <li class="code"><img src="{% static 'images/code.jpg' %}"/>#}
                {#                    <p class="center">扫描关注微信</p></li>#}
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">111111</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">慕学在线-在线学习交流平台</span>
            <span class="fr"></span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>


</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles  %}
{% block title %}首页-慕学在线网{% endblock %}
{% block custom_body%}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banner %}
                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">

                                    <li>
                                        <a href="course-detail.html">
                                            <img width="470" height="300" src="/static/media/courses/2016/12/python文件处理.jpg" />
                                        </a>
                                    </li>

                                    <li>
                                        <a href="course-detail.html">
                                            <img width="470" height="300" src="/static/media/courses/2016/12/python面向对象.jpg" />
                                        </a>
                                    </li>

								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="django入门">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'organization:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in orgs %}
                            <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                    <a href="{% url 'organization:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>全国知名</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="慕课网">{{ org.name }}</span></p>
                                    </a>
                        </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block customer_css %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}