MxOnline/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
import xadmin
from django.views.static import serve
from users.views import ActiveUserView, IndexView
from MxOnline.settings import MEDIA_ROOT
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('mxonline/xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # 用户url
    path('users/', include('users.urls', namespace='users')),
    # 用户激活
    re_path(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    # 图片验证码
    path('captcha/', include('captcha.urls')),
    # 课程机构
    path('org/', include('organization.urls', namespace='organization')),
    # 课程url
    path('course/', include('course.urls', namespace='course')),
    # 配置上传文件处理函数
    re_path(r'media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}),

    # 富文本url
    re_path(r'^mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 全局404
handler404 = 'users.views.page_not_found'
# 全局500
handler500 = 'users.views.page_error'

apps/course/urls.py
from django.urls import path
from .views import *
app_name = 'course'
urlpatterns = (
    path('course_list/', CourseListView.as_view(), name='course_list'),
    path('course_detail/<int:course_id>/', CourseDetailView.as_view(), name='course_detail'),
    # 开始学习
    path('course_video/<int:course_id>/', CourseVideoView.as_view(), name='course_video'),
    # 评论界面
    path('course_video_comment/<int:course_id>/', CommentCourseView.as_view(), name='course_video_comment'),
    # 添加评论
    path('add_comment/', AddCommentsView.as_view(), name='add_comment'),

    path('video/<int:video_id>/', VideoView.as_view(), name='video_play'),

)

apps/organization/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'organization'
urlpatterns = [
    # 课程机构url
    path('list/', OrgListView.as_view(), name='org_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    path('org_home/<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
    path('org_course/<int:org_id>/', OrgCourseView.as_view(), name='org_course'),
    path('org_desc/<int:org_id>/', OrgDescView.as_view(), name='org_desc'),
    path('org_teacher/<int:org_id>/', OrgTeacherView.as_view(), name='org_teacher'),
    # 机构收藏
    path('add_fav/', AddFavView.as_view(), name='add_fav'),
    # 讲师列表
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),

    path('teacher/detail/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
    # 分享
    path('share/message/', SendShareEmailView.as_view(), name='share'),
]

apps/users/urls.py
from django.urls import path, re_path
from .views import *
app_name = 'users'
urlpatterns = (
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # 忘记密码
    path('forget/', ForgetPwdView.as_view(), name='forget'),
    re_path(r'^reset/(?P<reset_code>.*)/$', ResetPwdView.as_view(), name='user_reset'),
    path('reset/', ResetView.as_view(), name='reset_pwd'),
    # 登出
    path('logout/', OutLoginView.as_view(), name='logout'),
    # 用户信息
    path('user_info/', UserInfoView.as_view(), name='user_info'),
    # 用户头像
    path('user/image/', UploadImageView.as_view(), name='user-image'),
    # 用户密码修改
    path('update/pwd/', ModifyPwdView.as_view(), name='update-pwd'),
    # 用户邮箱修改，发送邮箱验证码
    path('sendemail_code/', SendEmailView.as_view(), name='sendemail_code'),
    # 用户邮箱修改
    path('update_email/', ModifyEmailView.as_view(), name='update_email'),
    # 修改用户信息
    # path('info/', UserInfoView.as_view(), name='info'),
    # 用户课程
    path('user_course/', UserCourseView.as_view(), name='user_course'),
    # 用户收藏(机构，教师，课程)
    # re_path(r'^user_fav/(?P<fav_type>.*)/$', UserFavView.as_view(), name='user_fav'),
    # 用户收藏机构
    path('user_fav/org/', UserFavOrgView.as_view(), name='user_fav_org'),
    # 教师
    path('user_fav/teacher/', UserFavTeacherView.as_view(), name='user_fav_teacher'),
    # 课程
    path('user_fav/course/', UserFavCourseView.as_view(), name='user_fav_course'),
    # 用户消息
    path('user_message/', UserMessageView.as_view(), name='user_message'),

)

apps/course/models.py
from django.db import models
from datetime import datetime
from organization.models import Teacher, CourseOrg
from users.models import UserProfile
from mdeditor.fields import MDTextField

# Create your models here.


class CourseCategory(models.Model):
    name = models.CharField(max_length=64, verbose_name="课程类别名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程类别"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='教授机构', null=True, blank=True, on_delete=models.CASCADE)
    course_teacher = models.ForeignKey(Teacher, verbose_name='教授讲师', null=True, blank=True, on_delete=models.CASCADE)
    course_category = models.ForeignKey(CourseCategory, verbose_name="课程类别", on_delete=models.CASCADE)
    name = models.CharField(max_length=64, verbose_name="课程名")
    desc = models.CharField(max_length=256, verbose_name="课程描述")
    detail = MDTextField(verbose_name='课程详情')
    degree = models.CharField(verbose_name='难度', choices=(('cj', "初级"), ('zj', "中级"), ('gj', "高级")), max_length=32)
    learn_time = models.IntegerField(default=0, verbose_name="学习时长")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏人数")
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name="封面", blank=True)
    tag = models.CharField(default='', max_length=20, verbose_name="课程标签")
    click_nums = models.IntegerField(default=0, verbose_name="浏览量")
    known = MDTextField(verbose_name='课程须知', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_lesson(self):
        return self.lesson_set.all().count()

    def get_course_user(self):
        return self.usercourse_set.all()[:5]

    def save(self, *args, **kwargs):
        """
        将新增加的课程添加到课程机构
        :param args: 
        :param kwargs: 
        :return: 
        """
        self.course_org.course_nums += 1
        # 调用父类的 save 方法将数据保存到数据库中
        super(Course, self).save(*args, **kwargs)
        
    def increase_click_nums(self):
        self.click_nums += 1
        self.save(update_fields=['click_nums'])
        
    def increase_fav_nums(self):
        self.fav_nums += 1
        self.save(update_fields=['fav_nums'])
        
    def increase_students_nums(self):
        self.students += 1
        self.save(update_fields=['students'])


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name="章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course.name + ' ' + self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name="视频名")
    content = models.FileField(upload_to="videos/", null=True, blank=True, verbose_name="视频内容")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")
    # url = models.CharField(max_length=128, verbose_name="访问地址", default='')

    def __str__(self):
        return self.name

    def get_video_course(self):
        return self.lesson.course.name
    get_video_course.short_description = '课程名称'

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=32, verbose_name="名称")
    download = models.FileField(upload_to='course/resource/%X', verbose_name="资源")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 课程公告
class CourseAnnouncement(models.Model):
    course = models.ForeignKey(Course, verbose_name='公告课程', on_delete=models.CASCADE)
    text = models.CharField(max_length=200, default='', verbose_name='课程公告')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程公告"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course.name + '的课程公告。'

apps/users/models.py
# coding:utf-8
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=50, verbose_name="昵称", default="")
    birday = models.DateField(verbose_name="生日", null=True, blank=True)
    gender = models.CharField(choices=(('male', "男"), ('female', "女")), default="", max_length=6)
    address = models.CharField(max_length=100, default="")
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(upload_to='user/%Y/%m', default=u'image/default.png', max_length=128)

    class Meta:
        verbose_name = u'用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=24, verbose_name="验证码")
    email = models.EmailField(max_length=50, verbose_name="邮箱")
    send_type = models.CharField(verbose_name='验证类型', choices=(('register', "注册"), ('forget', "找回密码"),
                                                               ('update', "修改邮箱")), max_length=10)
    send_time = models.DateTimeField(verbose_name='发送时间', default=datetime.now)

    class Meta:
        verbose_name = u'邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.email


class Banner(models.Model):  # 首页轮播图
    title = models.CharField(max_length=100, verbose_name="标题")
    image = models.ImageField(upload_to='banner/%Y-%m-%d', verbose_name="轮播图")
    url = models.URLField(max_length=256, verbose_name="访问地址", null=True, blank=True)
    index = models.IntegerField(default=100, verbose_name="顺序")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5, max_length=16)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=6, max_length=16)
    # 图片验证码
    captcha = CaptchaField(error_messages={"invalid": '验证码错误'}, required=True)


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    # 图片验证码
    captcha = CaptchaField(error_messages={"invalid": '验证码错误'}, required=True)


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6, max_length=16)
    password2 = forms.CharField(required=True, min_length=6, max_length=16)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'birday', 'gender', 'address', 'mobile']

templates/user/active_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'index' %}"><h2>激活成功，返回首页</h2></a>
</body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>慕学在线网登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<div class="dialog" id="jsDialog">
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div  class="noactivebox dialogbox" id="jsUnactiveForm" >
    <h1>邮件验证提示</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="center">
        <img src="/static/images/send.png"/>
        <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
        <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
        <p class="zy_success upmove"></p>
        <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
        <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
    </div>
</div>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>111111</span></li>
                <li class="active"><a href=".">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'index' %}"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>帐号登录</h2>
                <form action="{% url 'users:login' %}" method="post" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 {% if login_form.errors.username %}errorput{% endif %}">
                        <label>用&nbsp;户&nbsp;名</label>
                        <input name="username" id="account_l" type="text" placeholder="手机号/邮箱"/>
                    </div>
                    <div class="form-group marb8 {% if login_form.errors.password %}errorput{% endif %}">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">{% for key,error in login_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                     <div class="auto-box marb38">

                        <a class="fr" href="{% url 'users:forget' %}">忘记密码？</a>
                     </div>
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                </form>
                <p class="form-p">没有慕学在线网帐号？<a href="{% url 'users:register' %}">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
</body>
</html>

templates/user/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'users:reset_pwd' %}" method="post">
            {% csrf_token %}
            <ul>
                <li>
                    <input type="hidden" name="email" value="{{ email }}">
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/user/reset_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'users:login' %}"><h2>密码重置成功，前往登陆</h2></a>


</body>
</html>

templates/user/usercenter-fav-course.html
{% extends 'user/user-base.html' %}
{% load staticfiles %}
{% block title %}
    我的收藏 - 慕学在线网
{% endblock %}

{% block break %}
    <li>我的收藏</li>
{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% ifequal fav_type 'org' %}active{% endifequal %}"><a href="{% url 'users:user_fav_org' %}">课程机构</a> </li>
                        <li class="{% ifequal fav_type 'teacher' %}active{% endifequal %}"><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                        <li class="{% ifequal fav_type 'course' %}active{% endifequal %}"><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in user_fav_course %}
                            <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_time }}小时</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" id="jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    <script type="application/javascript">
        $(document).ready(function () {
        $('.jsDeleteFav_course').on('click', function () {
            let fav_id = $(this).attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'organization:add_fav' %}",
                data: {
                    fav_type: 1,
                    fav_id: fav_id,
                },
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    alert('删除成功。');
                    Dml.fun.winReload();
                }
            });
        });
    });
    </script>
{% endblock %}

{% block info %}{% endblock %}

{% block js %}{% endblock %}

templates/user/usercenter-fav-org.html
{% extends 'user/user-base.html' %}
{% load staticfiles %}
{% block title %}
    我的收藏 - 慕学在线网
{% endblock %}

{% block break %}
    <li>我的收藏</li>
{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% ifequal fav_type 'org' %}active{% endifequal %}"><a href="{% url 'users:user_fav_org' %}">课程机构</a> </li>
                        <li class="{% ifequal fav_type 'teacher' %}active{% endifequal %}"><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                        <li class="{% ifequal fav_type 'course' %}active{% endifequal %}"><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in user_fav_org %}
                        <div class="messages butler_list company company-fav-box">
                            <dl class="des fr">
                                <dt>
                                    <a href="{% url 'organization:org_home' org.id %}">
                                        <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <h1><a href="{% url 'organization:org_home' org.id %}">{{ org.name }}</a></h1>
                                    <div class="pic fl" style="width:auto;">
                                        <img src="{% static 'images/authentication.png' %}"/>
                                        <img src="{% static 'images/gold.png' %}"/>
                                    </div>
                                    <span class="c8 clear">{{ org.address }}</span>
                                    <div class="delete jsDeleteFav_org" id="jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                                </dd>
                            </dl>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    <script type="application/javascript">
        $(document).ready(function () {
        $('#jsDeleteFav_org').on('click', function () {
            let fav_id = $(this).attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'organization:add_fav' %}",
                data: {
                    fav_type: 2,
                    fav_id: fav_id,
                },
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    alert('删除成功。');
                    Dml.fun.winReload();
                }
            });
        });
    });
    </script>
{% endblock %}

{% block info %}{% endblock %}

{% block js %}{% endblock %}

templates/user/usercenter-fav-teacher.html
{% extends 'user/user-base.html' %}
{% load staticfiles %}
{% block title %}
    我的收藏 - 慕学在线网
{% endblock %}

{% block break %}
    <li>我的收藏</li>
{% endblock %}
{% block right %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="{% ifequal fav_type 'org' %}active{% endifequal %}"><a
                            href="{% url 'users:user_fav_org' %}">课程机构</a></li>
                    <li class="{% ifequal fav_type 'teacher' %}active{% endifequal %}"><a
                            href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                    <li class="{% ifequal fav_type 'course' %}active{% endifequal %}"><a
                            href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for teacher in user_fav_teacher %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'organization:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'organization:org_home' teacher.org.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.course_set.all.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">收藏数：<span>{{ teacher.fav_nums }}</span></li>

                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" id="jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <script type="application/javascript">
        $(document).ready(function () {
        $('#jsDeleteFav_teacher').on('click', function () {
            let fav_id = $(this).attr('data-favid');

            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'organization:add_fav' %}",
                data: {
                    fav_type: 3,
                    fav_id: fav_id,
                },
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    alert('删除成功。');
                    Dml.fun.winReload();
                }
            });
        });
    });
    </script>
{% endblock %}

{% block info %}{% endblock %}

{% block js %}
{% endblock %}